# This workflow will run when a push occurs on main

name: Mantine Json View

on:
  push:
    branches:
      - main

env:
  NEEDS_PUBLISH: false

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - run: git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - run: git config user.name "$GITHUB_ACTOR"
      - run: PNPM_VERSION=$(node -p "require('./package.json').engines.pnpm")
      - run: npm install -g pnpm@$PNPM_VERSION
      - run: pnpm install --frozen-lockfile
      - run: pnpm test

      - if: ${{ contains(github.event.head_commit.message, 'patch:') }}
        run: pnpm version patch
        env:
          NEEDS_PUBLISH: true

      - if: ${{ contains(github.event.head_commit.message, 'minor:') }}
        run: pnpm version minor
        env:
          NEEDS_PUBLISH: true

      - if: ${{ contains(github.event.head_commit.message, 'major:') }}
        run: pnpm version major
        env:
          NEEDS_PUBLISH: true

      - run: VERSION=$(node -p "require('./package.json').version")
      - run: git tag ${VERSION}
        if: ${{ env.NEEDS_PUBLISH == 'true' }}
      - run: git push "https://$GITHUB_ACTOR:${{ secrets.ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --follow-tags
        if: ${{ env.NEEDS_PUBLISH == 'true' }}
      - run: git push "https://$GITHUB_ACTOR:${{ secrets.ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --tags
        if: ${{ env.NEEDS_PUBLISH == 'true' }}
      - run: pnpm build
        if: ${{ env.NEEDS_PUBLISH == 'true' }}
      - run: pnpm publish --access public
        if: ${{ env.NEEDS_PUBLISH == 'true' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
